# Generated by Django 4.1.4 on 2022-12-28 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_servicios.services')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Api_Payments',
            },
        ),
        migrations.CreateModel(
            name='Payments_expired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_payments.payments')),
                ('service_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_servicios.services')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Api_Payments_expired',
            },
        ),
    ]
